### ISSUE TITLE
Support for Fenix 7 Pro Sapphire?

### ISSUE THREAD

**Issue by lazodar** [zmullett/connectiq-sonos#4]
Hi I have been using this for a long time on my Vivoactive 3 Music, and was suprised to see my new fenix 7 pro sapphire was not compatible. Would it be possible to add this watch?
Thanks in advance :-)

**Comment by zmullett** [comment]
I attempted to just include **all** devices available in the latest SDK; https://github.com/zmullett/connectiq-sonos/commit/b30bea097307d6158807f59f6a1e3c7ba1a22165.

I didn't spot any device ID resembling "fenix 7 pro sapphire"... can you let me know if it works for you? The version ID 0.0.21 should contain this change.

**Comment by lazodar** [comment]
Wonderful! Got it installed and working. Thank you!

**Comment by lazodar** [comment]
(unit id according to my android version of connect is: "3451009999", with product name: "fenix 7 pro sapphire solar" no idea if this is helpful or not, but I thought I'd mention it)

**Comment by sjsmith16190** [comment]
I also am having troubles using the Fenix 7 pro solar sapphire! It just comes up with the name of the speaker group in the middle of the screen; can't bring up volume controls or anything like that... and also can't exit the app seemingly; always goes back to the screen it was on when I last left it.

**Comment by lazodar** [comment]
Strange, it is working fine on mine... when speaker name is on the screen, tap it, and the play button appears, tap that and it starts.
tap and hold, and the volume appears up and down buttons change the volume. Click back twice and the watch face appears. So if that does not work for you... I don't know what the problem is. Maybe the developer can help?

**Comment by zmullett** [comment]
Closing, as originally reported issue was resolved. @sjsmith16190 please see https://github.com/zmullett/connectiq-sonos/issues/4#issuecomment-1992404580.
