### ISSUE TITLE
Installation sonos app

### ISSUE THREAD

**Issue by Marquis1979** [zmullett/connectiq-sonos#6]
I can't find a select button, where Can I find it, are there any Screenshots available?

**Comment by zmullett** [comment]
Hi @Marquis1979,

"select" is unfortunately a misnomer from the device owner's perspective, however it's what Garmin generally calls it. It means different things depending on the device model; it's generally the action you take on the device to select something. On touchscreen watches without physical buttons this might be tapping the screen. On watches with only physical buttons it's the button that starts activities.

**Comment by Marquis1979** [comment]
![IMG_20240614_144148](https://github.com/zmullett/connectiq-sonos/assets/172788318/a93c0097-a7d6-429b-9319-8df0b04b0d11)


I get this screen on my watch, but I don't know what I should do then in the connect app on my phone, there is no select button in the app

**Comment by Marquis1979** [comment]
![IMG_20240614_144432](https://github.com/zmullett/connectiq-sonos/assets/172788318/0cb2b5aa-534d-44d5-a664-fd04fa0dfd79)

**Comment by Marquis1979** [comment]
Ok, I got it, I had to press the screen on my watch with the already opend connect app, then I get into the installation dialogue

**Comment by zmullett** [comment]
I think the phrasing could be improved to imply that the select action should be done on the device. Screen real-estate is at a premium on such devices but it's probably worth adding more detail to reduce confusion. Thanks for following up with some photographs!
