### ISSUE TITLE
Fenix 8 support - modify double tap button

### ISSUE THREAD

**Issue by Syntheticj** [zmullett/connectiq-sonos#8]
Trouble using this app on a Fenix 8, double clicking the menu button activates the voice command by default.  I'd rather have the option to choose which button to select the speaker group than change the shortcut buttons around on the watch.

**Comment by zmullett** [comment]
As far as I can tell, the widget code uses the standard approach to detecting menu invocation:

https://github.com/zmullett/connectiq-sonos/blob/6338fc99746c8f0171dcdd60a7f58dbfaa53c341/source/SonosGroupView.mc#L314

https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi/BehaviorDelegate.html#onMenu-instance_function

Adhering to that API offers the best compatibility across the range of Garmin devices. If Garmin wants to overload their buttons with new features, then I guess they'll be breaking some third-party apps 🤷  If anyone can offer an alternative that scales across their device range, we can try it out!
